"""Hypothesis Generator subsystem for formulating structured financial theories."""

from typing import List, Protocol, Type, TypeVar
from pydantic import BaseModel, Field

from synthra.core.domain import Hypothesis, HypothesisStatus
from synthra.research.planner import ResearchTask

T = TypeVar("T", bound=BaseModel)


class StructuredHypothesis(BaseModel):
    """Structured hypothesis schema generated by LLM guidance."""

    rationale: str = Field(..., min_length=10)
    target_variable: str = Field(..., min_length=1)
    datasets: List[str] = Field(..., min_length=1)
    operators: List[str] = Field(..., min_length=1)
    expected_market_behavior: str = Field(..., min_length=10)


class ILLMProvider(Protocol):
    """Protocol defining the interface for injectable LLM providers."""

    def generate_structured(
        self, system_prompt: str, user_prompt: str, response_model: Type[T]
    ) -> T:
        """Generate a structured response parsed into a Pydantic model."""
        ...


class HypothesisGenerator:
    """Hypothesis Generator subsystem to formulate structured trading hypotheses."""

    def __init__(self, llm_provider: ILLMProvider) -> None:
        """Initialize with an injected LLM provider."""
        self.llm_provider = llm_provider

    def generate_hypothesis(self, task: ResearchTask) -> StructuredHypothesis:
        """Call the LLM provider to construct a structured hypothesis for a task."""
        from synthra.research.prompts import (
            HYPOTHESIS_SYSTEM_PROMPT,
            HYPOTHESIS_USER_PROMPT,
        )

        user_prompt = HYPOTHESIS_USER_PROMPT.format(
            objective=task.objective,
            target_variable=task.target_variable,
            datasets=", ".join(task.assigned_datasets),
            operators=", ".join(task.assigned_operators),
            priority=task.priority,
        )

        # Generate structured output via LLM provider
        structured = self.llm_provider.generate_structured(
            system_prompt=HYPOTHESIS_SYSTEM_PROMPT,
            user_prompt=user_prompt,
            response_model=StructuredHypothesis,
        )
        return structured

    def to_domain(
        self,
        structured: StructuredHypothesis,
        campaign_id: str,
        hypothesis_id: str,
    ) -> Hypothesis:
        """Map a StructuredHypothesis to the domain model."""
        return Hypothesis(
            id=hypothesis_id,
            campaign_id=campaign_id,
            rationale=structured.rationale,
            target_variable=structured.target_variable,
            datasets=structured.datasets,
            operators=structured.operators,
            status=HypothesisStatus.DRAFT,
        )


class MockLLMProvider:
    """Mock LLM provider returning deterministic responses."""

    def __init__(self) -> None:
        self.last_system_prompt: str = ""
        self.last_user_prompt: str = ""

    def generate_structured(
        self, system_prompt: str, user_prompt: str, response_model: Type[T]
    ) -> T:
        """Simulates structured generation returning matching mock objects."""
        self.last_system_prompt = system_prompt
        self.last_user_prompt = user_prompt

        # Check model type to return appropriate mock
        if response_model.__name__ == "StructuredHypothesis":
            return response_model(
                rationale=(
                    "Momentum anomalies exist in price-volume data "
                    "because of lagged information digestion."
                ),
                target_variable="returns",
                datasets=["pv"],
                operators=["ts_mean", "delay"],
                expected_market_behavior=(
                    "High 20-day returns predict positive next-day returns."
                ),
            )
        elif response_model.__name__ == "GeneratedExpressionResponse":
            # For expression generator
            return response_model(
                expressions=["ts_mean(close, 20) / open", "delay(returns, 1)"]
            )

        raise ValueError(f"Unknown response model: {response_model}")
